---
title: "Двойственность"
lang: ru
language: 
  ru:
    section-title-references: ""
pdf-engine: xelatex
format:
  html:
    toc: true
    toc-depth: 2
    include-in-header:
      text: |
        $$
        \newcommand{\cN}{\mathcal{N}}
        \DeclareMathOperator{\P}{\mathbb{P}}
        \DeclareMathOperator{\E}{\mathbb{E}}
        \DeclareMathOperator{\Var}{Var}
        \DeclareMathOperator{\Cov}{Cov}
        \newcommand{\abs}[1]{\left\lvert #1 \right\rvert}
        $$
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{mathtools}
        \newcommand{\cN}{\mathcal{N}}

        \let\P\relax
        \DeclareMathOperator{\P}{\mathbb{P}}
        \DeclareMathOperator{\E}{\mathbb{E}}
        \DeclareMathOperator{\plim}{plim}
        \DeclareMathOperator{\Var}{Var}
        \DeclareMathOperator{\Cov}{Cov}
        \DeclareMathOperator{\Corr}{Corr}
        
        \DeclarePairedDelimiter{\norm}{\lVert}{\rVert}
        \DeclarePairedDelimiter{\abs}{\lvert}{\rvert}
        \DeclarePairedDelimiter{\scalp}{\langle}{\rangle}
        % TODO: automatic scaling does not work in pdf???
        
        % TODO: no cyrillic font in section titles!
        \setmainfont{Linux Libertine}
        
        %\newfontfamily{\cyrillicfont}{Linux Libertine}
        %\newfontfamily{\cyrillicfonttt}{Linux Libertine}
        %\newfontfamily{\cyrillicfontsf}{Linux Libertine}
        %\newfontfamily{\cyrillicfontrm}{Linux Libertine}
        %\newfontfamily{\cyrillicfontbf}{Linux Libertine}
        %\newfontfamily{\cyrillicfontmd}{Linux Libertine}
        %\newfontfamily{\cyrillicfontit}{Linux Libertine}
        %\newfontfamily{\cyrillicfontsl}{Linux Libertine}
        %\newfontfamily{\cyrillicfontsc}{Linux Libertine}
        %\newfontfamily{\cyrillicfontup}{Linux Libertine}
bibliography: references.bib
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

::: {.content-hidden}
\newcommand{\cN}{\mathcal{N}}
\DeclareMathOperator{\P}{\mathbb{P}}
\DeclareMathOperator{\E}{\mathbb{E}}
\DeclareMathOperator{\Var}{Var}
\DeclareMathOperator{\Cov}{Cov}
\newcommand{\abs}[1]{\left\lvert #1 \right\rvert}
\newcommand{\scalp}[1]{\langle #1 \rangle}
:::


# Двойственная функция

::: {.callout-note}
## Определение двойственной функции 

Двойственная функция в точке $x^*$ показывает, насколько минимум надо опустить 
прямую (или плоскость) $\scalp{x, x^*}$ вниз, чтобы она целиком оказалась ниже функции $f(x)$. 

$$
f^*(x^*) = \inf_t \{t \mid \scalp{x, x^*} - t \leq f(x), \text{ для любого } x\}
$$
Вектор $x^*$ содержит угловые коэффициенты прямой, которую мы двигаем. 
:::

Заметим, что определение легко переформулировать как поиск максимальной разницы от функции $f(x)$ вверх до прямой $\scalp{x, x^*}$.
Если в какой-то точке $x$ прямая $\scalp{x, x^*}$ лежит очень высоко относительно функции $f(x)$, то и минимальная величина, на которую придется опустить прямую очень велика. 

::: {.callout-note}
## Двойственная функция 

Двойственная функция в точке $x^*$ показывает, насколько минимум надо опустить 
прямую $\scalp{x, x^*}$ вниз, чтобы она целиком оказалась ниже функции $f(x)$. 

$$
f^*(x^*) = \sup_x \{\scalp{x, x^*} - f(x)\}
$$
:::

Конечно, двойственная функция может принимать особое значение $\infty$. 

Примеры.


::: {.callout-note}
## Упражнение

Как изменится двойственная функция, если сдвинуть исходную функцию на вектор $b$ вдоль аргументов?
:::

::: {.callout-caution collapse='true'}
## Решение упражнения

Определим сдвинутую функцию $g(x) = f(x - b)$.

Находим $g^*(x^*)$:
$$
g^*(x^*) = \sup_x \{\scalp{x, x^*} - g(x)\} = \sup_x \{\scalp{x, x^*} - f(x - b)\} 
$$

Прибавим и вычтем $\scalp{x, b}$:
$$
g^*(x^*) = \sup_x \{\scalp{x - b, x^*} - f(x - b)\} + \scalp{b, x^*} = \sup_{w} \{\scalp{w, x^*} - f(w)\} + \scalp{b, x^*}
$$

Следовательно,
$$
g^*(x^*) = f^*(x^*) + \scalp{b, x^*}
$$
:::



::: {.callout-note}
## Теоремка 

$$
f^{**}(x) \leq f(x)
$$
:::


::: {.callout-warning collapse="true"}
## Доказательство неравенства

Для доказательства теоремы предположим, что $f(x) \leq a$, 
и докажем, что в этом случае $f^{**}(x) \leq a$. 

На старт:
$$
f(x) \leq a
$$

Превратим левую и правую часть во что-то похожее на определение двойственной функции,
рассмотрев произвольные угловые коэффициенты $x^*$. 
$$
\scalp{x, x^*} - f(x) \geq \scalp{x, x^*} - a
$$


Левая часть не упадёт, если мы в ней вместо конкретного $x$ возьмём супремум:
$$
\sup_{w}\scalp{w, x^*} - f(w) \geq \scalp{x, x^*} - a
$$

Это в чистом виде определение $f^*(x^*)$:
$$
f^*(x^*) \geq \scalp{x, x^*} - a
$$
Вспомним, что вектор наклонов $x^*$ был произвольным!

Получается, что для любого вектора $x^*$:
$$
\scalp{x, x^*} - f^*(x^*) \leq a
$$

Если $a$ выше каждого возможного значения левой части, то $a$ выше максимально возможного. 
$$
\sup_{x^*}\{\scalp{x, x^*} - f^*(x^*)\} \leq a
$$

А это и есть искомое утверждение:
$$
f^{**}(x) \leq a.
$$
:::


Для хороших выпуклых функций, оказывается, что $f(x)=f^{**}(x)$.

::: {.callout-note}
## Теоремка 
Если ...., то
$$
f^{**}(x) = f(x)
$$
:::


::: {.callout-warning collapse="true"}
## Доказательство случая равенства

В доказательстве теоремки о неравенстве есть только один неравносильный переход. 
Обратим на него внимание. 

:::


# Двойственная задача

::: {.callout-note}

## Правильное определение двойственной задачи 

Рассмотрим задачу поиска минимума функции $\phi$ по $x$ с параметром $y$.
$$
\min_x \phi(x, y)
$$
Параметр $y$ мы воспринимаем как возмущение, отклонение задачи от некоторой исходной.

Исходная задача без возмущения имеет вид:
$$
\min_x \phi(x, 0)
$$

Двойственной задачей назовём задачу:
$$
\min_{y^*} \phi^*(0, y^*)
$$
:::

Заметим, что двойственная задача определена только после того, как мы договорились, как вносить возмущения в исходную задачу. 
Для разного типа возмущений будут возникать разные двойственные задачи. 



## Интуиция про штрафы и бонусы


## Интуиция про жёсткие и мягкие ограничения



## Линейное программирование 


## Попытка ограничить целевую функцию 


## SVM


# Нырнём обратно в общее определение


Определим функцию $h(y)$ как оптимум исходной задачи про возмущении $y$, 
$$
h(y) = \min_x \phi(x, y)
$$

В этом случае исходную задачу без возмущения можно представить как вычисление $h(0)$.


...

Таким образом, двойственная задача — это вычисление $h^{**}(0)$.

Помимо ещё одной абстрактной формулировки:

::: {.callout-note}
## Правильное определение двойственной задачи 

Рассмотрим задачу поиска минимума функции $\phi$ по $x$ с параметром $y$.
$$
h(y) = \min_x \phi(x, y)
$$

Прямая задача — это поиск $h(0)$.

Двойственная задача — это поиск $h^{**}(0)$.
:::

Вспомним, что $h^{**}(x) \leq h(x)$ для всех функций и $h^{**}(x) = h(x)$ для хороших ... функций. 

Следовательно, мы бесплатно получаем две теоремки:

::: {.callout-note}
## Теоремка 
Если $h(y) = \min_x \phi(x, y)$ — оптимум возмущённой задачи, то
$$
h^{**}(0) = \min_{y^*} \phi^*(0, y^*) \leq \min_x \phi(x, 0) = h(0).
$$
:::


::: {.callout-note}
## Теоремка 
Если $h(y) = \min_x \phi(x, y)$ — оптимум возмущённой задачи, и
...,
то
$$
h^{**}(0) = \min_{y^*} \phi^*(0, y^*) = \min_x \phi(x, 0) = h(0).
$$
:::



Источники:


